### ISSUE TITLE
Whether the "NOXIM" simulator can be used in CENTOS 7 platform or it strictly designed only for UBUNTU

### ISSUE THREAD

**Issue by ramapati166** [davidepatti/noxim#131]
I have tried to install NOXIM simulator in CENTOS 7 ,it is got installed but when I am trying to run it ,it is showing error and as result I could not be able to get the result.Is it possible to use  "NOXIM" simulator  in CENTOS 7 platform or it strictly designed only for UBUNTU?If anyone has faced the issue or solved it please suggest your valuable advice.

**Comment by davidepatti** [comment]
yes, it is absolutely possible to compile and run noxim on every unix systems, e.g. any gnu/linux distribution, or even macosx.
The script that you find in:
https://github.com/davidepatti/noxim/blob/master/other/setup/ubuntu.sh

it's only for ubuntu, but you can easily do one of these things:
1) read the above script and perfome each step manually. The only thing that should change it's only the command for installing packets, for example using "yum" instead of debian/ubuntu "apt install"
2) OR, clone the repository and follow the instructions in INSTALL.txt
3) OR, install a virtual machine with ubuntu and execute noxim form there.
