### ISSUE TITLE
Is Same Virtual is being used from Input router to the Ouput Router ???

### ISSUE THREAD

**Issue by chaitusvk** [davidepatti/noxim#134]
Hi ,

i am newbie , 

while Reading Tx process in Router ... i understood that 

1.  while Reservation you are Rasing request for  OUTPORT and **VC_ID of NEXT_ROUTER INPUT PORT** 
2. But in in reservation method which reserve You are including request.
While forwarding 

`int o = reservations[rnd_idx].first;
int vc = reservations[rnd_idx].second;`

**this reservation suppose tobe with VC corresponding to NEXT_ROUTER_INPUT VC**  please confirm me ..

But `if (!buffer[i][vc].IsEmpty())  `   Checking for  VC in Present router Port Buffer 
& `(buffer_full_status_tx[o].read().mask[vc] == false) ) ` and Cheking for Same VC as in Present Router With NEXT_ROUTER 

Have You Updated Flit VC_ID any where ??

i think this is not Truely Virtual Channel Protocal ...  it is Worm hole Routing 

i am Newbie . If i am wrong .. am Sorry

**Comment by davidepatti** [comment]
First of all, VC and Wormhole are not mutually exclusive: you can use VC in wormhole, VC it's just a way to allocate physical buffers between different flows. When not specifying the usage of VCs, you actually use them anyway, but there's only one single VC.
As for the meaning of the vc values, I suggest you to enable verbose log mode by uncommenting this line on bin/Makefile
`#DEBUG    :=  -g -DDEBUG`

then redirect the output so that you can follow the story of each single flit and understand what's going on:
`./noxim <some parameters> > mylog.txt`

**Comment by chaitusvk** [comment]
Thank you ...
