### ISSUE TITLE
Tile-Hub-Tile

### ISSUE THREAD

**Issue by setat** [davidepatti/noxim#46]
Hi,
In which part of the source code, I can find Tile-Hub-Tile process?
I mean if source tile and destination tile connect to the same hub, we have tile-hub-tile connection,
where can I find this part?

If in hub.cpp, which part of the code exactly?
----------------
Hub.cpp......>In this part, line 403:
void Hub::tileToAntennaProcess()
{....
403: r_from_tile[i] = route(flit);
...}
we can have two answers for route(flit);
1-port number which the destination tile is connected or 2- DIRECTION_WIRELESS
we only use DIRECTION_WIRELESS
what if we have "port number which the destination tile is connected" as the returned of route(flit)?

**Comment by davidepatti** [comment]
In the current routing strategies implemented, you go to wireless direction when  destination is connected to a different hub. Otherwise you continue to the next hop using wired. It's like driving by car (wired) and discovering that you have reached an airport that has a direct flight to another airport. Of course, any other strategy could be implemented in noxim by adding some code.
